-- P5 + P6 ONLINE: EINMAL vollständig im Supabase SQL Editor ausführen.
-- Bestehende P6-Buchungen und gesetzte Häkchen bleiben erhalten.

create table if not exists public.p6_bookings (
  dedupe_key text primary key,
  booking_id text not null default '',
  name text not null default '',
  phone text not null default '',
  email text not null default '',
  pricing text not null default '',
  from_raw text not null default '',
  from_date date,
  from_time text not null default '',
  to_raw text not null default '',
  to_date date,
  to_time text not null default '',
  booking_status text not null default '',
  parking text not null default 'P6',
  referral text not null default '',
  source_row integer,
  source_file text not null default '',
  check_in_completed boolean not null default false,
  check_out_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Fehlende Spalten bei einer älteren Installation ergänzen.
alter table public.p6_bookings add column if not exists booking_id text not null default '';
alter table public.p6_bookings add column if not exists name text not null default '';
alter table public.p6_bookings add column if not exists phone text not null default '';
alter table public.p6_bookings add column if not exists email text not null default '';
alter table public.p6_bookings add column if not exists pricing text not null default '';
alter table public.p6_bookings add column if not exists from_raw text not null default '';
alter table public.p6_bookings add column if not exists from_date date;
alter table public.p6_bookings add column if not exists from_time text not null default '';
alter table public.p6_bookings add column if not exists to_raw text not null default '';
alter table public.p6_bookings add column if not exists to_date date;
alter table public.p6_bookings add column if not exists to_time text not null default '';
alter table public.p6_bookings add column if not exists booking_status text not null default '';
alter table public.p6_bookings add column if not exists parking text not null default 'P6';
alter table public.p6_bookings add column if not exists referral text not null default '';
alter table public.p6_bookings add column if not exists source_row integer;
alter table public.p6_bookings add column if not exists source_file text not null default '';
alter table public.p6_bookings add column if not exists check_in_completed boolean not null default false;
alter table public.p6_bookings add column if not exists check_out_completed boolean not null default false;
alter table public.p6_bookings add column if not exists created_at timestamptz not null default now();
alter table public.p6_bookings add column if not exists updated_at timestamptz not null default now();
alter table public.p6_bookings alter column parking set default 'P6';

create table if not exists public.p6_imports (
  id bigint generated by default as identity primary key,
  file_name text not null,
  fingerprint text not null default '',
  csv_rows integer not null default 0,
  p5_rows integer not null default 0,
  p6_rows integer not null default 0,
  imported_at timestamptz not null default now()
);

alter table public.p6_imports add column if not exists fingerprint text not null default '';
alter table public.p6_imports add column if not exists csv_rows integer not null default 0;
alter table public.p6_imports add column if not exists p5_rows integer not null default 0;
alter table public.p6_imports add column if not exists p6_rows integer not null default 0;
alter table public.p6_imports add column if not exists imported_at timestamptz not null default now();

-- Alte Check-Constraints entfernen, falls eine frühere Version nur P6 zugelassen hat.
do $$
declare c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.p6_bookings'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%parking%'
  loop
    execute format('alter table public.p6_bookings drop constraint if exists %I', c.conname);
  end loop;
end $$;

alter table public.p6_bookings
  drop constraint if exists p6_bookings_parking_allowed;

alter table public.p6_bookings
  add constraint p6_bookings_parking_allowed
  check (parking in ('P5', 'P6'));

create index if not exists p6_bookings_parking_from_date_idx
  on public.p6_bookings (parking, from_date);
create index if not exists p6_bookings_parking_to_date_idx
  on public.p6_bookings (parking, to_date);
create index if not exists p6_bookings_parking_status_idx
  on public.p6_bookings (parking, booking_status);

alter table public.p6_bookings enable row level security;
alter table public.p6_imports enable row level security;

-- Alle alten Policies entfernen, besonders frühere P6-only-Policies.
do $$
declare p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'p6_bookings'
  loop
    execute format('drop policy if exists %I on public.p6_bookings', p.policyname);
  end loop;
end $$;

create policy "P5 P6 public read"
  on public.p6_bookings for select
  to anon, authenticated
  using (parking in ('P5', 'P6'));

create policy "P5 P6 public insert"
  on public.p6_bookings for insert
  to anon, authenticated
  with check (parking in ('P5', 'P6'));

create policy "P5 P6 public update"
  on public.p6_bookings for update
  to anon, authenticated
  using (parking in ('P5', 'P6'))
  with check (parking in ('P5', 'P6'));

do $$
declare p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'p6_imports'
  loop
    execute format('drop policy if exists %I on public.p6_imports', p.policyname);
  end loop;
end $$;

create policy "P5 P6 imports public read"
  on public.p6_imports for select
  to anon, authenticated
  using (true);

create policy "P5 P6 imports public insert"
  on public.p6_imports for insert
  to anon, authenticated
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.p6_bookings to anon, authenticated;
grant select, insert on public.p6_imports to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Kontrolle: Nach erneutem CSV-Upload müssen hier P5 und P6 erscheinen.
select parking, count(*) as buchungen
from public.p6_bookings
group by parking
order by parking;
