-- HOTELTRANSFERS FÜR P5 UND P6
-- Diese Datei EINMAL vollständig im Supabase SQL Editor ausführen.
-- Bestehende CSV-Buchungen und gesetzte Häkchen bleiben unverändert erhalten.

create table if not exists public.hotel_transfers (
  id bigint generated by default as identity primary key,
  parking text not null,
  guest_name text not null,
  persons integer not null default 1,
  transfer_date date not null,
  transfer_time time without time zone not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Falls die Tabelle aus einem früheren Test bereits vorhanden ist:
alter table public.hotel_transfers add column if not exists parking text;
alter table public.hotel_transfers add column if not exists guest_name text;
alter table public.hotel_transfers add column if not exists persons integer not null default 1;
alter table public.hotel_transfers add column if not exists transfer_date date;
alter table public.hotel_transfers add column if not exists transfer_time time without time zone;
alter table public.hotel_transfers add column if not exists completed boolean not null default false;
alter table public.hotel_transfers add column if not exists created_at timestamptz not null default now();
alter table public.hotel_transfers add column if not exists updated_at timestamptz not null default now();

alter table public.hotel_transfers
  drop constraint if exists hotel_transfers_parking_allowed;
alter table public.hotel_transfers
  add constraint hotel_transfers_parking_allowed
  check (parking in ('P5', 'P6'));

alter table public.hotel_transfers
  drop constraint if exists hotel_transfers_persons_allowed;
alter table public.hotel_transfers
  add constraint hotel_transfers_persons_allowed
  check (persons between 1 and 99);

create index if not exists hotel_transfers_parking_date_time_idx
  on public.hotel_transfers (parking, transfer_date, transfer_time);

alter table public.hotel_transfers enable row level security;

-- Alte Test-Policies entfernen.
do $$
declare p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'hotel_transfers'
  loop
    execute format('drop policy if exists %I on public.hotel_transfers', p.policyname);
  end loop;
end $$;

create policy "Hoteltransfers public read"
  on public.hotel_transfers for select
  to anon, authenticated
  using (parking in ('P5', 'P6'));

create policy "Hoteltransfers public insert"
  on public.hotel_transfers for insert
  to anon, authenticated
  with check (
    parking in ('P5', 'P6')
    and persons between 1 and 99
  );

create policy "Hoteltransfers public update"
  on public.hotel_transfers for update
  to anon, authenticated
  using (parking in ('P5', 'P6'))
  with check (
    parking in ('P5', 'P6')
    and persons between 1 and 99
  );

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.hotel_transfers to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Kontrolle: Diese Abfrage darf ohne Fehler laufen.
select parking, count(*) as hoteltransfers
from public.hotel_transfers
group by parking
order by parking;
