-- P6 Tagesliste: einmal vollständig im Supabase SQL Editor ausführen.

create table if not exists public.p6_bookings (
  dedupe_key text primary key,
  booking_id text not null default '',
  name text not null default '',
  phone text not null default '',
  email text not null default '',
  pricing text not null default '',
  from_raw text not null default '',
  from_date date,
  from_time text not null default '',
  to_raw text not null default '',
  to_date date,
  to_time text not null default '',
  booking_status text not null default '',
  parking text not null default 'P6',
  referral text not null default '',
  source_row integer,
  source_file text not null default '',
  check_in_completed boolean not null default false,
  check_out_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists p6_bookings_from_date_idx
  on public.p6_bookings (from_date);
create index if not exists p6_bookings_to_date_idx
  on public.p6_bookings (to_date);
create index if not exists p6_bookings_parking_status_idx
  on public.p6_bookings (parking, booking_status);

create table if not exists public.p6_imports (
  id bigint generated by default as identity primary key,
  file_name text not null,
  fingerprint text not null default '',
  csv_rows integer not null default 0,
  p6_rows integer not null default 0,
  imported_at timestamptz not null default now()
);

alter table public.p6_bookings enable row level security;
alter table public.p6_imports enable row level security;

-- Diese Anwendung hat absichtlich keine Anmeldung.
-- Jeder Besucher mit dem Link und dem öffentlichen Supabase-Key kann lesen/schreiben.
drop policy if exists "P6 public read" on public.p6_bookings;
create policy "P6 public read"
  on public.p6_bookings for select
  to anon, authenticated
  using (true);

drop policy if exists "P6 public insert" on public.p6_bookings;
create policy "P6 public insert"
  on public.p6_bookings for insert
  to anon, authenticated
  with check (parking = 'P6');

drop policy if exists "P6 public update" on public.p6_bookings;
create policy "P6 public update"
  on public.p6_bookings for update
  to anon, authenticated
  using (parking = 'P6')
  with check (parking = 'P6');

drop policy if exists "P6 imports public read" on public.p6_imports;
create policy "P6 imports public read"
  on public.p6_imports for select
  to anon, authenticated
  using (true);

drop policy if exists "P6 imports public insert" on public.p6_imports;
create policy "P6 imports public insert"
  on public.p6_imports for insert
  to anon, authenticated
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.p6_bookings to anon, authenticated;
grant select, insert on public.p6_imports to anon, authenticated;
grant usage, select on sequence public.p6_imports_id_seq to anon, authenticated;
